/**
 * Guard: `db/schema-objects.json` — the list of every named database object that
 * `tools/check_schema_citations.py` resolves citations against — is exactly what the migrations build,
 * read from PostgreSQL's catalogue.
 *
 * WHY (findings S3 and S4, Rule 21.9)
 *
 * The citation tool used to parse the migrations' SQL to learn what exists. It never forgot a dropped
 * index (S3: a comment citing `acceptance_issue_key`, dropped by J13, still "resolved"), and its parsing
 * missed ordinary DDL forms (S4). So it no longer parses: it reads this file, and this test regenerates
 * the file from the real catalogue and fails if the committed copy differs. A dropped object leaves the
 * catalogue, so it leaves the file, so a citation to it fails.
 *
 * To refresh after a migration: `PRYVIS_WRITE_SCHEMA_OBJECTS=1 npx vitest run test/schema-objects.test.ts`
 * in new-app/db, then commit the file. Without the variable this test only compares.
 *
 * WHAT IT DOES NOT PROVE (Rule 21.4)
 *
 * - Not settings (GUCs such as the balance-write flag): they are not catalogue objects. The tool still
 *   finds those by reading `current_setting(...)` and `set_config(...)` calls in the migrations.
 * - Not that a cited object is the right one for the sentence that cites it.
 */
import { PGlite } from "@electric-sql/pglite";
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

import { applyMigrations, MIGRATIONS_DIR } from "../test-support/index.js";

const FILE = join(MIGRATIONS_DIR, "..", "schema-objects.json");

type Objects = {
  note: string;
  schemas: string[];
  /** Tables, partitioned tables, views, materialised views and foreign tables, with their columns. */
  tables: Record<string, string[]>;
  sequences: string[];
  types: string[];
  functions: string[];
  triggers: string[];
  policies: string[];
  indexes: string[];
  constraints: string[];
  /** PostgreSQL's own function names, so a migration comment citing `md5()` resolves (T1). */
  builtin_functions: string[];
};

async function names(db: PGlite, sql: string): Promise<string[]> {
  return (await db.query<{ n: string }>(sql)).rows.map((r) => r.n);
}

/**
 * Every user schema, not only public (finding T8: a table, view, enum or sequence elsewhere was
 * invisible and the freshness test still passed). An object outside public is named schema.name.
 */
const USER_NS = `n.nspname NOT LIKE 'pg\\_%' AND n.nspname <> 'information_schema'`;
const QUALIFIED = (name: string) => `CASE WHEN n.nspname = 'public' THEN ${name} ELSE n.nspname || '.' || ${name} END`;

describe("the object list the citation tool reads is what the migrations build", () => {
  let db: PGlite;
  let built: Objects;

  beforeAll(async () => {
    db = new PGlite();
    await applyMigrations(db);
    const columns = (
      await db.query<{ t: string; c: string }>(
        `SELECT ${QUALIFIED("c.relname")} AS t, a.attname AS c
           FROM pg_attribute a JOIN pg_class c ON c.oid = a.attrelid JOIN pg_namespace n ON n.oid = c.relnamespace
          WHERE ${USER_NS} AND c.relkind IN ('r', 'p', 'v', 'm', 'f') AND a.attnum > 0 AND NOT a.attisdropped
          ORDER BY 1, 2`,
      )
    ).rows;
    const tables: Record<string, string[]> = {};
    for (const { t, c } of columns) (tables[t] ??= []).push(c);
    built = {
      note:
        "GENERATED by new-app/db/test/schema-objects.test.ts from the catalogue after every migration. " +
        "Never edit by hand; tools/check_schema_citations.py resolves citations against it.",
      schemas: await names(db, `SELECT n.nspname AS n FROM pg_namespace n WHERE ${USER_NS} ORDER BY 1`),
      tables,
      sequences: await names(
        db,
        `SELECT ${QUALIFIED("c.relname")} AS n FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
          WHERE ${USER_NS} AND c.relkind = 'S' ORDER BY 1`,
      ),
      types: await names(
        db,
        `SELECT ${QUALIFIED("t.typname")} AS n FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
          WHERE ${USER_NS} AND t.typtype IN ('e', 'd', 'c', 'r', 'm')
            AND NOT EXISTS (SELECT 1 FROM pg_class c WHERE c.reltype = t.oid) ORDER BY 1`,
      ),
      functions: await names(
        db,
        `SELECT DISTINCT ${QUALIFIED("p.proname")} AS n FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
          WHERE ${USER_NS} ORDER BY 1`,
      ),
      triggers: await names(
        db,
        `SELECT DISTINCT t.tgname AS n FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
           JOIN pg_namespace n ON n.oid = c.relnamespace WHERE ${USER_NS} AND NOT t.tgisinternal ORDER BY 1`,
      ),
      policies: await names(
        db,
        `SELECT DISTINCT p.polname AS n FROM pg_policy p JOIN pg_class c ON c.oid = p.polrelid
           JOIN pg_namespace n ON n.oid = c.relnamespace WHERE ${USER_NS} ORDER BY 1`,
      ),
      indexes: await names(
        db,
        `SELECT ${QUALIFIED("c.relname")} AS n FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
          WHERE ${USER_NS} AND c.relkind IN ('i', 'I') ORDER BY 1`,
      ),
      constraints: await names(
        db,
        `SELECT DISTINCT k.conname AS n FROM pg_constraint k JOIN pg_namespace n ON n.oid = k.connamespace
          WHERE ${USER_NS} ORDER BY 1`,
      ),
      builtin_functions: await names(
        db,
        `SELECT DISTINCT proname AS n FROM pg_proc WHERE pronamespace = 'pg_catalog'::regnamespace ORDER BY 1`,
      ),
    };
    if (process.env.PRYVIS_WRITE_SCHEMA_OBJECTS === "1") {
      await writeFile(FILE, JSON.stringify(built, null, 2) + "\n");
    }
  });

  afterAll(async () => {
    await db.close();
  });

  it("read the schema at all", () => {
    expect(Object.keys(built.tables).length).toBeGreaterThan(20);
    expect(built.functions.length).toBeGreaterThan(5);
  });

  it("matches the committed file — refresh it with PRYVIS_WRITE_SCHEMA_OBJECTS=1 after a migration", async () => {
    const committed = JSON.parse(await readFile(FILE, "utf8")) as Objects;
    expect(committed).toEqual(built);
  });
});
