/**
 * Guard: `db/schema-objects.json` — the list of every named database object that
 * `tools/check_schema_citations.py` resolves citations against — is exactly what the migrations build,
 * read from PostgreSQL's catalogue.
 *
 * WHY (findings S3 and S4, Rule 21.9)
 *
 * The citation tool used to parse the migrations' SQL to learn what exists. It never forgot a dropped
 * index (S3: a comment citing `acceptance_issue_key`, dropped by J13, still "resolved"), and its parsing
 * missed ordinary DDL forms (S4). So it no longer parses: it reads this file, and this test regenerates
 * the file from the real catalogue and fails if the committed copy differs. A dropped object leaves the
 * catalogue, so it leaves the file, so a citation to it fails.
 *
 * To refresh after a migration: `PRYVIS_WRITE_SCHEMA_OBJECTS=1 npx vitest run test/schema-objects.test.ts`
 * in new-app/db, then commit the file. Without the variable this test only compares.
 *
 * WHAT IT DOES NOT PROVE (Rule 21.4)
 *
 * - Not settings (GUCs such as the balance-write flag): they are not catalogue objects. The tool still
 *   finds those by reading `current_setting(...)` and `set_config(...)` calls in the migrations.
 * - Not that a cited object is the right one for the sentence that cites it.
 */
import { PGlite } from "@electric-sql/pglite";
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

import { applyMigrations, MIGRATIONS_DIR } from "../test-support/index.js";

const FILE = join(MIGRATIONS_DIR, "..", "schema-objects.json");

type Objects = {
  note: string;
  tables: Record<string, string[]>;
  functions: string[];
  triggers: string[];
  policies: string[];
  indexes: string[];
  constraints: string[];
};

async function names(db: PGlite, sql: string): Promise<string[]> {
  return (await db.query<{ n: string }>(sql)).rows.map((r) => r.n);
}

describe("the object list the citation tool reads is what the migrations build", () => {
  let db: PGlite;
  let built: Objects;

  beforeAll(async () => {
    db = new PGlite();
    await applyMigrations(db);
    const pub = `(SELECT oid FROM pg_namespace WHERE nspname = 'public')`;
    const columns = (
      await db.query<{ t: string; c: string }>(
        `SELECT c.relname AS t, a.attname AS c
           FROM pg_attribute a JOIN pg_class c ON c.oid = a.attrelid
          WHERE c.relnamespace = ${pub} AND c.relkind = 'r' AND a.attnum > 0 AND NOT a.attisdropped
          ORDER BY 1, 2`,
      )
    ).rows;
    const tables: Record<string, string[]> = {};
    for (const { t, c } of columns) (tables[t] ??= []).push(c);
    built = {
      note:
        "GENERATED by new-app/db/test/schema-objects.test.ts from the catalogue after every migration. " +
        "Never edit by hand; tools/check_schema_citations.py resolves citations against it.",
      tables,
      functions: await names(db, `SELECT DISTINCT proname AS n FROM pg_proc WHERE pronamespace = ${pub} ORDER BY 1`),
      triggers: await names(
        db,
        `SELECT DISTINCT t.tgname AS n FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
          WHERE c.relnamespace = ${pub} AND NOT t.tgisinternal ORDER BY 1`,
      ),
      policies: await names(
        db,
        `SELECT DISTINCT p.polname AS n FROM pg_policy p JOIN pg_class c ON c.oid = p.polrelid
          WHERE c.relnamespace = ${pub} ORDER BY 1`,
      ),
      indexes: await names(db, `SELECT relname AS n FROM pg_class WHERE relnamespace = ${pub} AND relkind = 'i' ORDER BY 1`),
      constraints: await names(db, `SELECT DISTINCT conname AS n FROM pg_constraint WHERE connamespace = ${pub} ORDER BY 1`),
    };
    if (process.env.PRYVIS_WRITE_SCHEMA_OBJECTS === "1") {
      await writeFile(FILE, JSON.stringify(built, null, 2) + "\n");
    }
  });

  afterAll(async () => {
    await db.close();
  });

  it("read the schema at all", () => {
    expect(Object.keys(built.tables).length).toBeGreaterThan(20);
    expect(built.functions.length).toBeGreaterThan(5);
  });

  it("matches the committed file — refresh it with PRYVIS_WRITE_SCHEMA_OBJECTS=1 after a migration", async () => {
    const committed = JSON.parse(await readFile(FILE, "utf8")) as Objects;
    expect(committed).toEqual(built);
  });
});
