/**
 * CORE: auth — the second factor for our own staff.
 *
 * Owns:        enrolment, confirmation, verification, recovery codes, and the lock that follows a
 *              person rather than a session.
 * Trusts:      core/auth/totp for the arithmetic, secret-box for the sealing, the rate limiter for
 *              the first line on guessing, core/audit for the record.
 * Never does:  offer a way to disable a factor; tell a caller whether a code was wrong or the
 *              account was locked; log a code.
 *
 * WHY STAFF AND NOT EVERYONE (Rule 5.1)
 *
 * The asymmetry is the argument: a tenant losing their password loses their own data; a staff
 * member losing theirs loses EVERYBODY's, because the console can suspend a tenant, change pricing
 * and impersonate. Tenants did not choose our staff's password hygiene. So a factor is offered to
 * tenants and required of anyone holding a platform capability — and "required" means the resolver
 * refuses them, not that a policy document says so.
 *
 * THERE IS NO disableMfa()
 *
 * Deliberately absent, and it should stay absent. A lost device is recovery codes; if those are
 * gone too it is a re-enrolment performed by another staff member holding a specific capability,
 * audited, with sessions revoked. A support path that removes a factor over a phone call is the
 * standard way MFA is defeated in practice, and the way to not have one is to not write it.
 */
import { createHash, randomBytes } from "node:crypto";

import { record, type AuditAction } from "../audit/audit.js";
import { RATE_LIMITS, type RateLimiter } from "../rate-limit/rate-limiter.js";
import { KeyRegistry, needsResealing, open, seal } from "./secret-box.js";
import { newTotpSecret, totpProvisioningUri, verifyTotp } from "./totp.js";
import type { TransactionalClient } from "../tenancy/tenant-context.js";

/**
 * Consecutive failures before the factor locks, and for how long.
 *
 * Five is chosen for a person, not for an attacker: somebody reading a code off a phone as it
 * rolls over will occasionally submit a stale one, and locking them out on the second attempt
 * would make the product feel broken. A million possible codes against five attempts and a
 * fifteen-minute lock is a guessing rate of roughly one in thirty thousand per day.
 *
 * The lock FOLLOWS THE PERSON. The rate limiter bounds attempts per session and per IP and is the
 * first line; this survives a new session, so an attacker cannot reset their budget by signing in
 * again with a password they have already stolen.
 */
export const MFA_MAX_FAILURES = 5;
export const MFA_LOCK_MINUTES = 15;

/** How recently a factor must have been proved for a dangerous action (Rule 5.1). */
export const MFA_REAUTH_MINUTES = 15;

/** How many recovery codes an enrolment produces. */
export const RECOVERY_CODE_COUNT = 10;

export class MfaError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "MfaError";
  }
}

/**
 * What a caller is told when verification fails, whatever the reason.
 *
 * One sentence for a wrong code, a replayed code, a locked factor and an exhausted limiter.
 * Distinguishing them would tell someone working through codes whether to keep going, and would
 * tell an attacker with a stolen password that the account exists and is protected.
 */
export const MFA_FAILED_MESSAGE = "That code is not right. Try the current one from your app.";

export interface MfaQueryable extends TransactionalClient {
  $queryRawUnsafe<T>(query: string, ...values: unknown[]): Promise<T[]>;
}

/** Why a verification was refused. For the audit trail and the log, never for the caller. */
export type MfaFailure =
  | "no-factor"
  | "not-confirmed"
  | "locked"
  | "rate-limited"
  | "wrong-code"
  | "replayed-code"
  | "used-recovery-code";

export interface MfaEnrolment {
  /** Shown once, as a QR code and as text for manual entry. */
  readonly provisioningUri: string;
  readonly secret: string;
}

export interface RecoveryCodes {
  /** Shown once. We keep only hashes. */
  readonly codes: readonly string[];
}

interface FactorRow {
  secret_ciphertext: Buffer;
  secret_iv: Buffer;
  secret_tag: Buffer;
  secret_key_id: string;
  confirmed_at: Date | null;
  last_used_step: string | null;
  failed_attempts: number;
  locked_until: Date | null;
}

/**
 * A recovery code: 20 base32 characters, in groups of four.
 *
 * About 100 bits of randomness, generated by us rather than chosen by a person — which is why it is
 * hashed with SHA-256 and no salt rather than with scrypt. There is no dictionary to try and no
 * reuse across sites, so a slow hash defends against nothing here, while generating ten at scrypt's
 * cost would mean 670 MB of work to enrol one person.
 */
const RECOVERY_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; // no I, O, 0, 1 — they get misread

function newRecoveryCode(): string {
  const bytes = randomBytes(20);
  const characters = [...bytes].map((b) => RECOVERY_ALPHABET[b % RECOVERY_ALPHABET.length]).join("");
  return characters.match(/.{1,5}/g)!.join("-");
}

/** Normalised before hashing, because people retype these from paper. */
export function normaliseRecoveryCode(code: string): string {
  return code.replace(/[\s-]/g, "").toUpperCase();
}

export function hashRecoveryCode(code: string): string {
  return createHash("sha256").update(normaliseRecoveryCode(code)).digest("hex");
}

export class MfaService {
  constructor(
    private readonly db: MfaQueryable,
    private readonly keys: KeyRegistry,
    private readonly limiter: RateLimiter,
    private readonly newId: () => string,
    private readonly now: () => Date = () => new Date(),
  ) {}

  /**
   * Does this user hold any platform capability, and therefore require a factor?
   *
   * Asked of the database on every sign-in rather than cached on the user: a capability granted an
   * hour ago must require a factor now, and a capability revoked must stop requiring one. Same
   * reasoning as re-resolving the role (ADR 0013).
   */
  async requiresFactor(tx: MfaQueryable, userId: string): Promise<boolean> {
    const rows = await tx.$queryRawUnsafe<{ holds: boolean }>(
      `SELECT EXISTS (
         SELECT 1 FROM platform_capability
          WHERE user_id = $1 AND revoked_at IS NULL
       ) AS holds`,
      userId,
    );
    return rows[0]?.holds === true;
  }

  /** Is there a confirmed factor? An unconfirmed one protects nobody. */
  async hasConfirmedFactor(tx: MfaQueryable, userId: string): Promise<boolean> {
    const rows = await tx.$queryRawUnsafe<{ confirmed: boolean }>(
      `SELECT EXISTS (
         SELECT 1 FROM mfa_totp WHERE user_id = $1 AND confirmed_at IS NOT NULL
       ) AS confirmed`,
      userId,
    );
    return rows[0]?.confirmed === true;
  }

  /**
   * Issues a secret and the provisioning URI. **Grants nothing on its own.**
   *
   * An unconfirmed factor means a secret was issued and may never have reached a phone, so the
   * resolver keeps refusing the user until `confirm` succeeds. Re-enrolling replaces an
   * unconfirmed secret — somebody who abandoned the flow halfway should not be stuck with a secret
   * they never scanned — but never a confirmed one, which is what `reset` is for.
   */
  async beginEnrolment(
    tx: MfaQueryable,
    options: { userId: string; tenantId: string; accountEmail: string },
  ): Promise<MfaEnrolment> {
    if (await this.hasConfirmedFactor(tx, options.userId)) {
      throw new MfaError(
        "This account already has a confirmed second factor. Replacing it is a reset, which " +
          "another staff member performs and which revokes this person's sessions.",
      );
    }

    const secret = newTotpSecret();
    const sealed = seal(this.keys, secret);

    await tx.$executeRawUnsafe(
      `INSERT INTO mfa_totp
         (user_id, secret_ciphertext, secret_iv, secret_tag, secret_key_id, updated_at)
       VALUES ($1, $2, $3, $4, $5, now())
       ON CONFLICT (user_id) DO UPDATE
         SET secret_ciphertext = EXCLUDED.secret_ciphertext,
             secret_iv = EXCLUDED.secret_iv,
             secret_tag = EXCLUDED.secret_tag,
             secret_key_id = EXCLUDED.secret_key_id,
             failed_attempts = 0,
             locked_until = NULL,
             last_used_step = NULL,
             updated_at = now()
         WHERE mfa_totp.confirmed_at IS NULL`,
      options.userId,
      sealed.ciphertext,
      sealed.iv,
      sealed.tag,
      sealed.keyId,
    );

    return {
      secret,
      provisioningUri: totpProvisioningUri({
        issuer: "Pryvis",
        account: options.accountEmail,
        secret,
      }),
    };
  }

  /**
   * Confirms enrolment with a real code, then issues recovery codes.
   *
   * Requiring a code is what makes enrolment mean something: it proves the secret reached an
   * authenticator rather than being issued and forgotten.
   */
  async confirmEnrolment(
    tx: MfaQueryable,
    options: { userId: string; tenantId: string; code: string; actorIp?: string | null },
  ): Promise<RecoveryCodes> {
    const factor = await this.loadFactor(tx, options.userId);
    if (!factor) throw new MfaError("There is no enrolment in progress for this account.");
    if (factor.confirmed_at) throw new MfaError("This factor is already confirmed.");

    const secret = open(this.keys, {
      keyId: factor.secret_key_id,
      ciphertext: factor.secret_ciphertext,
      iv: factor.secret_iv,
      tag: factor.secret_tag,
    });

    const checked = verifyTotp(secret, options.code, Math.floor(this.now().getTime() / 1000));
    if (!checked.valid) throw new MfaError(MFA_FAILED_MESSAGE);

    await tx.$executeRawUnsafe(
      `UPDATE mfa_totp
          SET confirmed_at = now(), last_used_step = $2, failed_attempts = 0,
              locked_until = NULL, updated_at = now()
        WHERE user_id = $1`,
      options.userId,
      String(checked.step),
    );

    const codes = Array.from({ length: RECOVERY_CODE_COUNT }, newRecoveryCode);
    for (const code of codes) {
      await tx.$executeRawUnsafe(
        `INSERT INTO mfa_recovery_code (id, user_id, code_hash) VALUES ($1, $2, $3)`,
        this.newId(),
        options.userId,
        hashRecoveryCode(code),
      );
    }

    await this.audit(tx, options, "user.mfa_enrolled", "Confirmed a second factor and received recovery codes");
    return { codes };
  }

  /**
   * Verifies a code — or a recovery code — and returns whether the session may proceed.
   *
   * Refusals are indistinguishable to the caller. Internally they are recorded, because "locked"
   * and "wrong code" are very different things to whoever is investigating.
   */
  async verify(
    tx: MfaQueryable,
    options: { userId: string; tenantId: string; sessionId: string; code: string; actorIp?: string | null },
  ): Promise<{ ok: true } | { ok: false; failure: MfaFailure; message: string }> {
    const refuse = (failure: MfaFailure) =>
      ({ ok: false as const, failure, message: MFA_FAILED_MESSAGE });

    // The limiter first, before any HMAC or hash: the expensive work must be what is protected.
    const limited = await this.limiter.consume(
      `mfa:user:${options.userId}`,
      RATE_LIMITS.signInPerEmail,
    );
    if (!limited.allowed) return refuse("rate-limited");

    const factor = await this.loadFactor(tx, options.userId);
    if (!factor) return refuse("no-factor");
    if (!factor.confirmed_at) return refuse("not-confirmed");
    if (factor.locked_until && factor.locked_until.getTime() > this.now().getTime()) {
      return refuse("locked");
    }

    const secret = open(this.keys, {
      keyId: factor.secret_key_id,
      ciphertext: factor.secret_ciphertext,
      iv: factor.secret_iv,
      tag: factor.secret_tag,
    });

    const checked = verifyTotp(secret, options.code, Math.floor(this.now().getTime() / 1000));

    if (checked.valid) {
      // A code is valid for its whole step, so "correct" is not "unused". Without this, a code
      // read over a shoulder or captured in transit works again inside the same 30 seconds.
      if (factor.last_used_step !== null && Number(factor.last_used_step) >= checked.step!) {
        await this.registerFailure(tx, options, "replayed-code");
        return refuse("replayed-code");
      }

      await tx.$executeRawUnsafe(
        `UPDATE mfa_totp
            SET last_used_step = $2, failed_attempts = 0, locked_until = NULL, updated_at = now()
          WHERE user_id = $1`,
        options.userId,
        String(checked.step),
      );
      await this.markSessionVerified(tx, options.sessionId);

      // Rotation, at the only moment the plaintext is in hand.
      if (needsResealing(this.keys, {
        keyId: factor.secret_key_id,
        ciphertext: factor.secret_ciphertext,
        iv: factor.secret_iv,
        tag: factor.secret_tag,
      })) {
        const resealed = seal(this.keys, secret);
        await tx.$executeRawUnsafe(
          `UPDATE mfa_totp
              SET secret_ciphertext = $2, secret_iv = $3, secret_tag = $4, secret_key_id = $5,
                  updated_at = now()
            WHERE user_id = $1`,
          options.userId,
          resealed.ciphertext,
          resealed.iv,
          resealed.tag,
          resealed.keyId,
        );
      }

      await this.limiter.reset(`mfa:user:${options.userId}`);
      return { ok: true };
    }

    // Not a TOTP code — try a recovery code before counting a failure, because a person using one
    // is doing the intended thing with a lost phone.
    const recovered = await this.consumeRecoveryCode(tx, options);
    if (recovered) {
      await this.markSessionVerified(tx, options.sessionId);
      await this.audit(
        tx,
        options,
        "user.mfa_recovery_code_used",
        "Signed in with a recovery code. The authenticator on the old device no longer works.",
      );
      return { ok: true };
    }

    await this.registerFailure(tx, options, "wrong-code");
    return refuse("wrong-code");
  }

  /**
   * Was this session's factor proved recently enough for a dangerous action? (Rule 5.1)
   *
   * `mfa_pending` answers "ever", which cannot answer this: a laptop walked away from has a session
   * that passed a factor hours ago, and starting an impersonation from it is exactly what this
   * prevents.
   */
  async hasRecentVerification(
    tx: MfaQueryable,
    sessionId: string,
    withinMinutes = MFA_REAUTH_MINUTES,
  ): Promise<boolean> {
    const rows = await tx.$queryRawUnsafe<{ recent: boolean }>(
      `SELECT (mfa_verified_at IS NOT NULL
               AND mfa_verified_at > ($2::timestamptz - ($3::text)::interval)) AS recent
         FROM app_session WHERE id = $1`,
      sessionId,
      this.now().toISOString(),
      `${withinMinutes} minutes`,
    );
    return rows[0]?.recent === true;
  }

  private async loadFactor(tx: MfaQueryable, userId: string): Promise<FactorRow | undefined> {
    const rows = await tx.$queryRawUnsafe<FactorRow>(
      `SELECT secret_ciphertext, secret_iv, secret_tag, secret_key_id, confirmed_at,
              last_used_step, failed_attempts, locked_until
         FROM mfa_totp WHERE user_id = $1`,
      userId,
    );
    return rows[0];
  }

  private async markSessionVerified(tx: MfaQueryable, sessionId: string): Promise<void> {
    await tx.$executeRawUnsafe(
      `UPDATE app_session SET mfa_pending = false, mfa_verified_at = $2 WHERE id = $1`,
      sessionId,
      this.now().toISOString(),
    );
  }

  private async consumeRecoveryCode(
    tx: MfaQueryable,
    options: { userId: string; code: string },
  ): Promise<boolean> {
    const hash = hashRecoveryCode(options.code);
    // Single-use, marked rather than deleted, and claimed in one statement so two concurrent
    // attempts cannot both spend the same code.
    const affected = await tx.$executeRawUnsafe(
      `UPDATE mfa_recovery_code
          SET used_at = now()
        WHERE user_id = $1 AND code_hash = $2 AND used_at IS NULL`,
      options.userId,
      hash,
    );
    return affected === 1;
  }

  private async registerFailure(
    tx: MfaQueryable,
    options: { userId: string; tenantId: string; actorIp?: string | null },
    failure: MfaFailure,
  ): Promise<void> {
    const rows = await tx.$queryRawUnsafe<{ failed_attempts: number }>(
      `UPDATE mfa_totp
          SET failed_attempts = failed_attempts + 1,
              locked_until = CASE
                WHEN failed_attempts + 1 >= $2 THEN ($3::timestamptz + ($4::text)::interval)
                ELSE locked_until
              END,
              updated_at = now()
        WHERE user_id = $1
        RETURNING failed_attempts`,
      options.userId,
      MFA_MAX_FAILURES,
      this.now().toISOString(),
      `${MFA_LOCK_MINUTES} minutes`,
    );

    const attempts = rows[0]?.failed_attempts ?? 0;
    if (attempts >= MFA_MAX_FAILURES) {
      await this.audit(
        tx,
        options,
        "user.mfa_locked",
        `Locked after ${MFA_MAX_FAILURES} consecutive failed second-factor attempts`,
      );
    }
  }

  /**
   * Writes the audit entry, never including the code.
   *
   * Obvious, and written down because the payload is exactly where a helpful debug field would put
   * it — and `details` is refused outright if it carries anything that looks like a credential
   * (ADR 0020).
   */
  private async audit(
    tx: MfaQueryable,
    options: { userId: string; tenantId: string; actorIp?: string | null },
    action: AuditAction,
    summary: string,
  ): Promise<void> {
    await record(
      tx,
      {
        tenantId: options.tenantId,
        actorKind: "tenant_user",
        actorUserId: options.userId,
        action,
        subject: { type: "app_user", id: options.userId },
        summary,
        ...(options.actorIp ? { actorIp: options.actorIp } : {}),
      },
      this.newId,
    );
  }
}
